DROP TABLE project;

CREATE TABLE project (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) UNIQUE NOT NULL,
    description varchar(250) NOT NULL,
    start DATE NOT NULL,
    person_id int REFERENCES person(id) ON DELETE SET NULL
);