CREATE TABLE person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(30) UNIQUE NOT NULL,
    password varchar NOT NULL ,
    first_name varchar(30) NOT NULL,
    last_name varchar(30) NOT NULL,
    role varchar (15) NOT NULL
)