DROP TABLE person;

CREATE TABLE person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(30) UNIQUE NOT NULL,
    password varchar NOT NULL ,
    first_name varchar(30) NOT NULL,
    last_name varchar(30) NOT NULL,
    email varchar(50) NOT NULL,
    role varchar (15) NOT NULL
);

TRUNCATE TABLE person;

INSERT INTO person(username, password, first_name, last_name, email, role)
VALUES ('admin', '$2a$12$RxrESzKINhrMtkz7.7awTeIbtvfogvEZ/bLmKcpxW2rvJc85ffiUu',
        'admin', 'admin', 'admin@mail.com','ROLE_ADMIN'),
        ('dev', '$2a$12$I7q7vKd7e7gCergPhf4Gt.VeMyXB3tcTNu6eqbD36AT.GNyyAPc9W',
            'developer','developer','dev@mail.com','ROLE_DEVELOPER');
